### ISSUE TITLE
Public testnet release tasks

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#355]
Documenting the tasks that should be in place for a public testnet release of the interface and extension here (some are already split into individual tasks, but we can use this issue to track overall progress)

Existing issues:

- [x] #353 Ledger error/rejection handling improvements
- [x] #354 Fix issues related to updating staking balances
- [x] #366  Redirect to `Login` if service worker goes inactive during `AddAccount` (mnemonic accounts only)
- [ ] #371 Must fix this issue with bech32 address validation!
- [ ] #349 Extension storage durability
- [x] #347 Faucet transfers for testnet extension (we can provide a faucet address in the deployment variables to determine if we display a faucet transfer form)
- [ ] #200 Implement connection approval (this is pretty straightforward, but not as important as other issues in here)
- [x] #356 Calls to service worker when service worker has shut down (Chrome) are still flaky in places - user shouldn't have to refresh (see `useUntil` and `executeUntil`) - This affects both functionality inside extension, in addition to the interface (approval launches can fail, and initial connection can fail if the service worker has shut down)
- [x] #358 Generic notifications - these should be consistent among each transaction type (including Ledger), where notification events are dispatched via the extension for feedback within the interface once the submission process begins
- [x] #357 __NOTE__ This would be nice if we could pull it off, but we should probably wait for Gianmarco to handle infrastructure-related tasks, as it would be beneficial to get this better integrated with Namada releases
- [x] #360 Update to `v0.21.x` - support Multisig changes in SDK
  -  This is ready as soon as we can point to `0.21.2` (once fix from Tomas in https://github.com/anoma/namada/pull/1828 is merged and released, as well as when the Ledger app supports 0.21.x tx)
  - Update to `v0.22.x` - if needed, incorporate any changes in SDK
- [x] #374 IBC transfers should be hooked up to approvals & Ledger

Additional tasks to scope out:
- IBC - we need to test Namada -> Cosmos ecosystem / Cosmos ecosystem -> Namada within a test network (Nam <> Osmosis | Cosmos | etc) - TODO
- Bridge - we need to implement and test Ethereum Bridge functionality - TODO
