### ISSUE TITLE
Namada SDK publish

### ISSUE THREAD

**Issue by mateuszjasiuk** [anoma/namada-interface#664]
### TODO
- [x] build and publish node version
  - [x] create proper node build script(with and without multicore FF)
  - [x] check publish script
- [x] build and publish web version
- [x] make both versions available for import at the same time
  - [ ] ~~make index separate entrypoint from init functions~~
  - [x] fix typings
- [x] use sdk-js-web in the extension

### Next issue

- [ ] ~~make examples use `dist`~~
- [ ] create sdk-examples package
- [ ] use sdk-js-node in the CLI tool
  - [ ] add "node" feature and implement persistence differently
- [ ] add [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) ?
- [ ] replace js snippets with rust libraries in shared
