### ISSUE TITLE
Prepare Namadillo for v0.1 release

### ISSUE THREAD

**Issue by pedrorezende** [anoma/namada-interface#863]
This issue lists the remaining tasks for the first release version for Namadillo (v0.1).

## General
- [x] Traffic lighting system #995 
- [x] #870
- [x] #926
- [x] Update logo
- [x] #916
- [x] #772 
- [x] Rounded corners on ActionButton hover
- [x] #888
- [x] Handle batch transactions and their respective toast notifications
- [x] Refactor store 
- [x] Fetch Chain ID, token address, and RPC Url from the indexer
- [x] Add toggle to set custom RPC Url
- [x] Display instructions if indexer chainId mismatches the extension chainId
- [x] Test accounts with zero balances, how indexer behaves, and fix potential errors
- [x] Remove Namada footer from the bottom
- [x] Sign Arbitrary message should be moved to its own page
- [x] Remove fiat currencies from settings
- [x] #876
- [x] #877
- [x] #869
- [x] #865
- [x] #872
- [x] #839
- [x] #975 - Batch Tx fees are incorrect, will need an update on Namadillo & Indexer

## Staking
- [x] Re-enable fee estimation
- [x] Add warning message if users aren't considering the fee amount necessary for staking
- [x] #866
- [x] Add correct APR data
- [x] Filter inactive / jailed validators

## Governance
- [ ] #806 - Bug, non-blocking for release
- [x] Use dates instead of epochs for proposal times
- [x] #798 
  - Temporarily removed panel. Not essential for release.
- [x] Readd search/filtering on the proposals table
- [X] Toast doesn't react to proposal vote transaction being successful
- [x] Turnout doesn't seem to be right
  - Not sure what I was seeing but it seems fine now
- [x] Review number of http queries on Governance page
  - Removed redundant queries when fetching all proposals

## Extension/SDK
- [x] #1000 UI update for buttons
- [x] Support Namada 0.40.0 (if 0.41.0 becomes launch version, uncheck this and update)
- [x] Implement signing updates for Ledger - This will need to be updated once Ledger App is working on Namada `v0.40.0`!
- [x] UI Tweaks on list of Tx details
- [ ] Prepare release for the stores
- [x] Implement Tx batch signing
- [x] Add back Tx details

## Indexer
- [x] Add query for wasm code paths + wasm checksum hashes (In progress: https://github.com/anoma/namada-interface/issues/923)
- [x] Return status of a bond
- [x] Getting status as "pending" after the start epoch - intermittent
- [x] Create endpoint to query chainId, rpcUrl, and nativeToken
- [x] Proposal startTime and endTime change on every call - Comment(@mateuszjasiuk) - this will change as we can only estimate time of future epochs
- [x] Proposal IDs should start from 0, not 1 - intermittent
- [x] Fee estimation endpoint

**Comment by euharrison** [comment]
@pedrorezende how about if we use these filters to get this list updated?

https://github.com/anoma/namada-interface/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3A%22App%3A+Interface%22
